# [TUGAS MAHASISWA] Ganti nilai di bawah ini dengan Organization Key dan Project Key dari akun SonarCloud Anda.
# Anda akan mendapatkan key ini setelah membuat project baru di https://sonarcloud.io dan menautkannya dengan repository GitHub Anda.
sonar.organization=GANTI_DENGAN_ORG_KEY_ANDA
sonar.projectKey=GANTI_DENGAN_PROJECT_KEY_ANDA

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=dist/**,coverage/**,node_modules/**
